//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group_members
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> member_id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
