//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Groups = new HashSet<Group>();
            this.member_application = new HashSet<member_application>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> supervisor_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string description { get; set; }
        public System.DateTime deadline { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<member_application> member_application { get; set; }
        public virtual User User { get; set; }
    }
}
